local Tags = {
  ['Absorb-STR'] = { 'Dark', 'Absorb', 'Absorb-STR' },
  ['Absorb-DEX'] = { 'Dark', 'Absorb', 'Absorb-DEX' },
  ['Absorb-VIT'] = { 'Dark', 'Absorb', 'Absorb-VIT' },
  ['Absorb-AGI'] = { 'Dark', 'Absorb', 'Absorb-AGI' },
  ['Absorb-INT'] = { 'Dark', 'Absorb', 'Absorb-INT' },
  ['Absorb-MND'] = { 'Dark', 'Absorb', 'Absorb-MND' },
  ['Absorb-CHR'] = { 'Dark', 'Absorb', 'Absorb-CHR' },
  ['Absorb-ACC'] = { 'Dark', 'Absorb', 'Absorb-ACC' },
  ['Absorb-TP'] = { 'Dark', 'Absorb', 'Absorb-TP' },

  -- Absorb Points Spells
  ['Drain'] = { 'Dark', 'AbsorbPoints', 'Drain' },
  ['Drain II'] = { 'Dark', 'AbsorbPoints', 'Drain' },
  ['Aspir'] = { 'Dark', 'AbsorbPoints', 'Aspir' },

  -- Elemental Damage Spells
  ['Aero'] = { 'Elemental', 'Nuke', 'Aero' },
  ['Aero II'] = { 'Elemental', 'Nuke', 'Aero' },
  ['Aero II '] = { 'Elemental', 'Nuke', 'Aero' },
  ['Aero IV'] = { 'Elemental', 'Nuke', 'Aero' },
  ['Tornado'] = { 'Elemental', 'Nuke', 'Tornado' },
  ['Tornado II'] = { 'Elemental', 'Nuke', 'Tornado' },
  ['Aeroga'] = { 'Elemental', 'Nuke', 'Aeroga' },
  ['Aeroga II'] = { 'Elemental', 'Nuke', 'Aeroga' },
  ['Aeroga III'] = { 'Elemental', 'Nuke', 'Aeroga' },
  ['Blizzard'] = { 'Elemental', 'Nuke', 'Blizzard' },
  ['Blizzard II'] = { 'Elemental', 'Nuke', 'Blizzard' },
  ['Blizzard III'] = { 'Elemental', 'Nuke', 'Blizzard' },
  ['Blizzard IV'] = { 'Elemental', 'Nuke', 'Blizzard' },
  ['Freeze'] = { 'Elemental', 'Nuke', 'Freeze' },
  ['Freeze II'] = { 'Elemental', 'Nuke', 'Freeze' },
  ['Blizzaga'] = { 'Elemental', 'Nuke', 'Blizzaga' },
  ['Blizzaga II'] = { 'Elemental', 'Nuke', 'Blizzaga' },
  ['Blizzaga III'] = { 'Elemental', 'Nuke', 'Blizzaga' },
  ['Fire'] = { 'Elemental', 'Nuke', 'Fire' },
  ['Fire II'] = { 'Elemental', 'Nuke', 'Fire' },
  ['Fire III'] = { 'Elemental', 'Nuke', 'Fire' },
  ['Fire IV'] = { 'Elemental', 'Nuke', 'Fire' },
  ['Flare'] = { 'Elemental', 'Nuke', 'Flare' },
  ['Flare II'] = { 'Elemental', 'Nuke', 'Flare' },
  ['Firaga'] = { 'Elemental', 'Nuke', 'Firaga' },
  ['Firaga II'] = { 'Elemental', 'Nuke', 'Firaga' },
  ['Firaga III'] = { 'Elemental', 'Nuke', 'Firaga' },
  ['Stone'] = { 'Elemental', 'Nuke', 'Stone' },
  ['Stone II'] = { 'Elemental', 'Nuke', 'Stone' },
  ['Stone III'] = { 'Elemental', 'Nuke', 'Stone' },
  ['Stone IV'] = { 'Elemental', 'Nuke', 'Stone' },
  ['Quake'] = { 'Elemental', 'Nuke', 'Quake' },
  ['Quake II'] = { 'Elemental', 'Nuke', 'Quake' },
  ['Stonega'] = { 'Elemental', 'Nuke', 'Stonega' },
  ['Stonega II'] = { 'Elemental', 'Nuke', 'Stonega' },
  ['Stonega III'] = { 'Elemental', 'Nuke', 'Stonega' },
  ['Thunder'] = { 'Elemental', 'Nuke', 'Thunder' },
  ['Thunder II'] = { 'Elemental', 'Nuke', 'Thunder' },
  ['Thunder III'] = { 'Elemental', 'Nuke', 'Thunder' },
  ['Thunder IV'] = { 'Elemental', 'Nuke', 'Thunder' },
  ['Burst'] = { 'Elemental', 'Nuke', 'Burst' },
  ['Burst II'] = { 'Elemental', 'Nuke', 'Burst' },
  ['Thundaga'] = { 'Elemental', 'Nuke', 'Thundaga' },
  ['Thundaga II'] = { 'Elemental', 'Nuke', 'Thundaga' },
  ['Thundaga III'] = { 'Elemental', 'Nuke', 'Thundaga' },
  ['Water'] = { 'Elemental', 'Nuke', 'Water' },
  ['Water II'] = { 'Elemental', 'Nuke', 'Water' },
  ['Water III'] = { 'Elemental', 'Nuke', 'Water' },
  ['Water IV'] = { 'Elemental', 'Nuke', 'Water' },
  ['Flood'] = { 'Elemental', 'Nuke', 'Flood' },
  ['Flood II'] = { 'Elemental', 'Nuke', 'Flood' },
  ['Waterga'] = { 'Elemental', 'Nuke', 'Waterga' },
  ['Waterga II'] = { 'Elemental', 'Nuke', 'Waterga' },
  ['Waterga III'] = { 'Elemental', 'Nuke', 'Waterga' },

  -- Ninjutsu Damage Spells
  ['Doton: Ichi'] = { 'Ninjutsu', 'ElementalNinjutsu', 'Doton' },
  ['Doton: Ni'] = { 'Ninjutsu', 'ElementalNinjutsu', 'Doton' },
  ['Doton: San'] = { 'Ninjutsu', 'ElementalNinjutsu', 'Doton' },
  ['Huton: Ichi'] = { 'Ninjutsu', 'ElementalNinjutsu', 'Huton' },
  ['Huton: Ni'] = { 'Ninjutsu', 'ElementalNinjutsu', 'Huton' },
  ['Huton: San'] = { 'Ninjutsu', 'ElementalNinjutsu', 'Huton' },
  ['Hyoton: Ichi'] = { 'Ninjutsu', 'ElementalNinjutsu', 'Hyoton' },
  ['Hyoton: Ni'] = { 'Ninjutsu', 'ElementalNinjutsu', 'Hyoton' },
  ['Hyoton: San'] = { 'Ninjutsu', 'ElementalNinjutsu', 'Hyoton' },
  ['Katon: Ichi'] = { 'Ninjutsu', 'ElementalNinjutsu', 'Katon' },
  ['Katon: Ni'] = { 'Ninjutsu', 'ElementalNinjutsu', 'Katon' },
  ['Katon: San'] = { 'Ninjutsu', 'ElementalNinjutsu', 'Katon' },
  ['Raiton: Ichi'] = { 'Ninjutsu', 'ElementalNinjutsu', 'Raiton' },
  ['Raiton: Ni'] = { 'Ninjutsu', 'ElementalNinjutsu', 'Raiton' },
  ['Raiton: San'] = { 'Ninjutsu', 'ElementalNinjutsu', 'Raiton' },
  ['Suiton: Ichi'] = { 'Ninjutsu', 'ElementalNinjutsu', 'Suiton' },
  ['Suiton: Ni'] = { 'Ninjutsu', 'ElementalNinjutsu', 'Suiton' },
  ['Suiton: San'] = { 'Ninjutsu', 'ElementalNinjutsu', 'Suiton' },

  -- Divine Damage Spells
  ['Banish'] = { 'Divine', 'Banish' },
  ['Banish II'] = { 'Divine', 'Banish' },
  ['Banish III'] = { 'Divine', 'Banish' },
  ['Banishga'] = { 'Divine', 'Banish', 'Banishga' },
  ['Banishga II'] = { 'Divine', 'Banish', 'Banishga' },
  ['Holy'] = { 'Divine', 'Holy' },
  ['Holy II'] = { 'Divine', 'Holy' },

  -- Enfeebling Songs
  ['Foe Requiem'] = { 'Song', 'EnfeeblingSong', 'Requiem', 'FoeRequiem' },
  ['Foe Requiem II'] = { 'Song', 'EnfeeblingSong', 'Requiem', 'FoeRequiem' },
  ['Foe Requiem III'] = { 'Song', 'EnfeeblingSong', 'Requiem', 'FoeRequiem' },
  ['Foe Requiem IV'] = { 'Song', 'EnfeeblingSong', 'Requiem', 'FoeRequiem' },
  ['Foe Requiem V'] = { 'Song', 'EnfeeblingSong', 'Requiem', 'FoeRequiem' },
  ['Foe Requiem VI'] = { 'Song', 'EnfeeblingSong', 'Requiem', 'FoeRequiem' },
  ['Foe Lullaby'] = { 'Song', 'EnfeeblingSong', 'Lullaby', 'FoeLullaby' },
  ['Horde Lullaby'] = { 'Song', 'EnfeeblingSong', 'Lullaby', 'HordeLullaby' },
  ['Magic Finale'] = { 'Song', 'EnfeeblingSong', 'Finale', 'MagicFinale' },
  ['Battlefield Elegy'] = {
    'Song',
    'EnfeeblingSong',
    'Elegy',
    'BattlefieldElegy',
  },
  ['Carnage Elegy'] = { 'Song', 'EnfeeblingSong', 'Elegy', 'CarnageElegy' },
  ['Fire Threnody'] = { 'Song', 'EnfeeblingSong', 'Threnody', 'FireThrenody' },
  ['Ice Threnody'] = { 'Song', 'EnfeeblingSong', 'Threnody', 'IceThrenody' },
  ['Wind Threnody'] = { 'Song', 'EnfeeblingSong', 'Threnody', 'WindThrenody' },
  ['Earth Threnody'] = { 'Song', 'EnfeeblingSong', 'Threnody', 'EarthThrenody' },
  ['Lightning Threnody'] = {
    'Song',
    'EnfeeblingSong',
    'Threnody',
    'LightningThrenody',
  },
  ['Water Threnody'] = { 'Song', 'EnfeeblingSong', 'Threnody', 'WaterThrenody' },
  ['Light Threnody'] = { 'Song', 'EnfeeblingSong', 'Threnody', 'LightThrenody' },
  ['Dark Threnody'] = { 'Song', 'EnfeeblingSong', 'Threnody', 'DarkThrenody' },
  ["Maiden's Virelai"] = {
    'Song',
    'EnfeeblingSong',
    'Virelai',
    'MaidensVirelai',
  },

  -- Enfeebling Spells
  ['Blind'] = { 'Enfeebling', 'BlackEnfeebling', 'Blind' },
  ['Blind II'] = { 'Enfeebling', 'BlackEnfeebling', 'Blind' },
  ['Dispel'] = { 'Enfeebling', 'BlackEnfeebling', 'Dispel' },
  ['Gravity'] = { 'Enfeebling', 'BlackEnfeebling', 'Gravity' },
  ['Poison'] = { 'Enfeebling', 'BlackEnfeebling', 'Poison' },
  ['Poison II'] = { 'Enfeebling', 'BlackEnfeebling', 'Poison' },
  ['Poisonga'] = { 'Enfeebling', 'BlackEnfeebling', 'Poison', 'Poisonga' },
  ['Poisonga II'] = { 'Enfeebling', 'BlackEnfeebling', 'Poison', 'Poisonga' },
  ['Sleep'] = { 'Enfeebling', 'BlackEnfeebling', 'Sleep' },
  ['Sleep II'] = { 'Enfeebling', 'BlackEnfeebling', 'Sleep' },
  ['Sleepga'] = { 'Enfeebling', 'BlackEnfeebling', 'Sleep', 'Sleepga' },
  ['Sleepga II'] = { 'Enfeebling', 'BlackEnfeebling', 'Sleep', 'Sleepga' },
  ['Paralyze'] = { 'Enfeebling', 'WhiteEnfeebling', 'Paralyze' },
  ['Paralyze II'] = { 'Enfeebling', 'WhiteEnfeebling', 'Paralyze' },
  ['Silence'] = { 'Enfeebling', 'WhiteEnfeebling', 'Silence' },
  ['Slow'] = { 'Enfeebling', 'WhiteEnfeebling', 'Slow' },
  ['Slow II'] = { 'Enfeebling', 'WhiteEnfeebling', 'Slow' },

  -- Elemental Debuff Spells
  ['Burn'] = { 'Elemental', 'ElementalDebuff', 'Burn' },
  ['Choke'] = { 'Elemental', 'ElementalDebuff', 'Choke' },
  ['Drown'] = { 'Elemental', 'ElementalDebuff', 'Drown' },
  ['Frost'] = { 'Elemental', 'ElementalDebuff', 'Frost' },
  ['Rasp'] = { 'Elemental', 'ElementalDebuff', 'Rasp' },
  ['Shock'] = { 'Elemental', 'ElementalDebuff', 'Shock' },

  -- Ninjutsu Enfeebling Spells
  ['Dokumori: Ichi'] = { 'Ninjutsu', 'DebuffNinjutsu', 'Dokumori' },
  ['Hojo: Ichi'] = { 'Ninjutsu', 'DebuffNinjutsu', 'Hojo' },
  ['Hojo: Ni'] = { 'Ninjutsu', 'DebuffNinjutsu', 'Hojo' },
  ['Jubaku: Ichi'] = { 'Ninjutsu', 'DebuffNinjutsu', 'Jubaku' },
  ['Kurayami: Ichi'] = { 'Ninjutsu', 'DebuffNinjutsu', 'Kurayami' },
  ['Kurayami: Ni'] = { 'Ninjutsu', 'DebuffNinjutsu', 'Kurayami' },

  -- Ninjutsu Enhancing Spells
  ['Monomi: Ichi'] = { 'Ninjutsu', 'EnhancingNinjutsu', 'Monomi' },
  ['Tonko: Ichi'] = { 'Ninjutsu', 'EnhancingNinjutsu', 'Tonko' },
  ['Tonko: Ni'] = { 'Ninjutsu', 'EnhancingNinjutsu', 'Tonko' },
  ['Utsusemi: Ichi'] = { 'Ninjutsu', 'EnhancingNinjutsu', 'Utsusemi' },
  ['Utsusemi: Ni'] = { 'Ninjutsu', 'EnhancingNinjutsu', 'Utsusemi' },

  -- Enhancing Songs
  ["Mage's Ballad"] = { 'Song', 'EnhancingSong', 'Ballad', 'MagesBallad' },
  ["Mage's Ballad II"] = { 'Song', 'EnhancingSong', 'Ballad', 'MagesBallad' },
  ['Fire Carol'] = { 'Song', 'EnhancingSong', 'Carol', 'FireCarol' },
  ['Ice Carol'] = { 'Song', 'EnhancingSong', 'Carol', 'IceCarol' },
  ['Wind Carol'] = { 'Song', 'EnhancingSong', 'Carol', 'WindCarol' },
  ['Earth Carol'] = { 'Song', 'EnhancingSong', 'Carol', 'EarthCarol' },
  ['Lightning Carol'] = { 'Song', 'EnhancingSong', 'Carol', 'LightningCarol' },
  ['Water Carol'] = { 'Song', 'EnhancingSong', 'Carol', 'WaterCarol' },
  ['Light Carol'] = { 'Song', 'EnhancingSong', 'Carol', 'LightCarol' },
  ['Dark Carol'] = { 'Song', 'EnhancingSong', 'Carol', 'DarkCarol' },
  ['Sinewy Etude'] = { 'Song', 'EnhancingSong', 'Etude', 'SinewyEtude' },
  ['Dextrous Etude'] = { 'Song', 'EnhancingSong', 'Etude', 'DextrousEtude' },
  ['Vivacious Etude'] = { 'Song', 'EnhancingSong', 'Etude', 'VivaciousEtude' },
  ['Quick Etude'] = { 'Song', 'EnhancingSong', 'Etude', 'QuickEtude' },
  ['Learned Etude'] = { 'Song', 'EnhancingSong', 'Etude', 'LearnedEtude' },
  ['Spirited Etude'] = { 'Song', 'EnhancingSong', 'Etude', 'SpiritedEtude' },
  ['Enchanting Etude'] = { 'Song', 'EnhancingSong', 'Etude', 'EnchantingEtude' },
  ['Herculean Etude'] = { 'Song', 'EnhancingSong', 'Etude', 'HerculeanEtude' },
  ['Uncanny Etude'] = { 'Song', 'EnhancingSong', 'Etude', 'UncannyEtude' },
  ['Vital Etude'] = { 'Song', 'EnhancingSong', 'Etude', 'VitalEtude' },
  ['Swift Etude'] = { 'Song', 'EnhancingSong', 'Etude', 'SwiftEtude' },
  ['Sage Etude'] = { 'Song', 'EnhancingSong', 'Etude', 'SageEtude' },
  ['Logical Etude'] = { 'Song', 'EnhancingSong', 'Etude', 'LogicalEtude' },
  ['Bewitching Etude'] = { 'Song', 'EnhancingSong', 'Etude', 'BewitchingEtude' },
  ['Sword Madrigal'] = { 'Song', 'EnhancingSong', 'Madrigal', 'SwordMadrigal' },
  ['Blade Madrigal'] = { 'Song', 'EnhancingSong', 'Madrigal', 'BladeMadrigal' },
  ['Sheepfoe Mambo'] = { 'Song', 'EnhancingSong', 'Mambo', 'SheepfoeMambo' },
  ['Dragonfoe Mambo'] = { 'Song', 'EnhancingSong', 'Mambo', 'DragonfoeMambo' },
  ['Advancing March'] = { 'Song', 'EnhancingSong', 'March', 'AdvancingMarch' },
  ['Victory March'] = { 'Song', 'EnhancingSong', 'March', 'VictoryMarch' },
  ["Knight's Minne"] = { 'Song', 'EnhancingSong', 'Minne', 'KnightsMinne' },
  ["Knight's Minne II"] = { 'Song', 'EnhancingSong', 'Minne', 'KnightsMinne' },
  ["Knight's Minne III"] = { 'Song', 'EnhancingSong', 'Minne', 'KnightsMinne' },
  ["Knight's Minne IV"] = { 'Song', 'EnhancingSong', 'Minne', 'KnightsMinne' },
  ['Valor Minuet'] = { 'Song', 'EnhancingSong', 'Minuet', 'ValorMinuet' },
  ['Valor Minuet II'] = { 'Song', 'EnhancingSong', 'Minuet', 'ValorMinuet' },
  ['Valor Minuet III'] = { 'Song', 'EnhancingSong', 'Minuet', 'ValorMinuet' },
  ['Valor Minuet IV'] = { 'Song', 'EnhancingSong', 'Minuet', 'ValorMinuet' },
  ["Army's Paeon"] = { 'Song', 'EnhancingSong', 'Paeon', 'ArmysPaeon' },
  ["Army's Paeon II"] = { 'Song', 'EnhancingSong', 'Paeon', 'ArmysPaeon' },
  ["Army's Paeon III"] = { 'Song', 'EnhancingSong', 'Paeon', 'ArmysPaeon' },
  ["Army's Paeon IV"] = { 'Song', 'EnhancingSong', 'Paeon', 'ArmysPaeon' },
  ["Army's Paeon V"] = { 'Song', 'EnhancingSong', 'Paeon', 'ArmysPaeon' },
  ["Hunter's Prelude"] = {
    'Song',
    'EnhancingSong',
    'Prelude',
    'HuntersPrelude',
  },
  ["Archer's Prelude"] = {
    'Song',
    'EnhancingSong',
    'Prelude',
    'ArchersPrelude',
  },
  ['Fowl Aubade'] = { 'Song', 'EnhancingSong', 'Aubade', 'FowlAubade' },
  ['Gold Capriccio'] = { 'Song', 'EnhancingSong', 'Capriccio', 'GoldCapriccio' },
  ['Goblin Gavotte'] = { 'Song', 'EnhancingSong', 'Gavotte', 'GoblinGavotte' },
  ["Scop's Operetta"] = { 'Song', 'EnhancingSong', 'Operetta', 'ScopsOperetta' },
  ["Puppet's Operetta"] = {
    'Song',
    'EnhancingSong',
    'Operetta',
    'PuppetsOperetta',
  },
  ['Herb Pastoral'] = { 'Song', 'EnhancingSong', 'Pastoral', 'HerbPastoral' },
  ['Shining Fantasia'] = {
    'Song',
    'EnhancingSong',
    'Fantasia',
    'ShiningFantasia',
  },
  ['Warding Round'] = { 'Song', 'EnhancingSong', 'Round', 'WardingRound' },
  ["Goddess's Hymnus"] = { 'Song', 'EnhancingSong', 'Hymnus', 'GoddesssHymnus' },
  ["Sentinel's Scherzo"] = {
    'Song',
    'EnhancingSong',
    'Scherzo',
    'SentinelsScherzo',
  },
  ['Raptor Mazurka'] = { 'Song', 'EnhancingSong', 'Mazurka', 'RaptorMazurka' },
  ['Chocobo Mazurka'] = { 'Song', 'EnhancingSong', 'Mazurka', 'ChocoboMazurka' },
  ['Foe Sirvente'] = { 'Song', 'EnhancingSong', 'Sirvente', 'Foe Sirvente' },
  ["Adventurer's Dirge"] = {
    'Song',
    'EnhancingSong',
    'Dirge',
    'AdventurersDirge',
  },

  -- Enhancing Spells
  ['Aquaveil'] = { 'Enhancing', 'Aquaveil' },
  ['Auspice'] = { 'Enhancing', 'Auspice' },
  ['Baraero'] = { 'Enhancing', 'BarSpell', 'BarElement', 'Baraero' },
  ['Barblizzard'] = { 'Enhancing', 'BarSpell', 'BarElement', 'Barblizzard' },
  ['Barfire'] = { 'Enhancing', 'BarSpell', 'BarElement', 'Barfire' },
  ['Barstone'] = { 'Enhancing', 'BarSpell', 'BarElement', 'Barstone' },
  ['Barthunder'] = { 'Enhancing', 'BarSpell', 'BarElement', 'Barthunder' },
  ['Barwater'] = { 'Enhancing', 'BarSpell', 'BarElement', 'Barwater' },
  ['Baraera'] = { 'Enhancing', 'BarSpell', 'BarElement', 'Baraera' },
  ['Barblizzara'] = { 'Enhancing', 'BarSpell', 'BarElement', 'Barblizzara' },
  ['Barfira'] = { 'Enhancing', 'BarSpell', 'BarElement', 'Barfira' },
  ['Barstonra'] = { 'Enhancing', 'BarSpell', 'BarElement', 'Barstonra' },
  ['Barthundra'] = { 'Enhancing', 'BarSpell', 'BarElement', 'Barthundra' },
  ['Batwatera'] = { 'Enhancing', 'BarSpell', 'BarElement', 'Batwatera' },
  ['Baramnesia'] = { 'Enhancing', 'BarSpell', 'BarEffect', 'Baramnesia' },
  ['Barblind'] = { 'Enhancing', 'BarSpell', 'BarEffect', 'Barblind' },
  ['Barparalyze'] = { 'Enhancing', 'BarSpell', 'BarEffect', 'Barparalyze' },
  ['Barpetrify'] = { 'Enhancing', 'BarSpell', 'BarEffect', 'Barpetrify' },
  ['Barpoison'] = { 'Enhancing', 'BarSpell', 'BarEffect', 'Barpoison' },
  ['Barsilence'] = { 'Enhancing', 'BarSpell', 'BarEffect', 'Barsilence' },
  ['Barvirus'] = { 'Enhancing', 'BarSpell', 'BarEffect', 'Barvirus' },
  ['Baramnesra'] = { 'Enhancing', 'BarSpell', 'BarEffect', 'Baramnesra' },
  ['Barblindra'] = { 'Enhancing', 'BarSpell', 'BarEffect', 'Barblindra' },
  ['Barparalyzra'] = { 'Enhancing', 'BarSpell', 'BarEffect', 'Barparalyzra' },
  ['Barpetra'] = { 'Enhancing', 'BarSpell', 'BarEffect', 'Barpetra' },
  ['Barpoisonra'] = { 'Enhancing', 'BarSpell', 'BarEffect', 'Barpoisonra' },
  ['Barsilencera'] = { 'Enhancing', 'BarSpell', 'BarEffect', 'Barsilencera' },
  ['Barsleepra'] = { 'Enhancing', 'BarSpell', 'BarEffect', 'Barsleepra' },
  ['Barvira'] = { 'Enhancing', 'BarSpell', 'BarEffect', 'Barvira' },
  ['Blink'] = { 'Blink' },
  ['Deodorize'] = { 'Stealth', 'Deodorize' },
  ['Sneak'] = { 'Stealth', 'Sneak' },
  ['Invisible'] = { 'Stealth', 'Invisible' },
  ['Enaero'] = { 'Enhancing', 'EnSpell', 'Enaero' },
  ['Enaero II'] = { 'Enhancing', 'EnSpell', 'Enaero' },
  ['Enblizzard'] = { 'Enhancing', 'EnSpell', 'Enblizzard' },
  ['Enblizzard II'] = { 'Enhancing', 'EnSpell', 'Enblizzard' },
  ['Enfire'] = { 'Enhancing', 'EnSpell', 'Enfire' },
  ['Enfire II'] = { 'Enhancing', 'EnSpell', 'Enfire' },
  ['Enstone'] = { 'Enhancing', 'EnSpell', 'Enstone' },
  ['Enstone II'] = { 'Enhancing', 'EnSpell', 'Enstone' },
  ['Enthunder'] = { 'Enhancing', 'EnSpell', 'Enthunder' },
  ['Enthunder II'] = { 'Enhancing', 'EnSpell', 'Enthunder' },
  ['Enwater'] = { 'Enhancing', 'EnSpell', 'Enwater' },
  ['Enwater II'] = { 'Enhancing', 'EnSpell', 'Enwater' },
  ['Enlight'] = { 'Enhancing', 'EnSpell', 'Enlight' },
  ['Haste'] = { 'Haste' },
  ['Phalanx'] = { 'Enhancing', 'Phalanx', 'Phalanx' },
  ['Phalanx II'] = { 'Enhancing', 'Phalanx', 'Phalanx' },
  ['Protect'] = { 'Protect' },
  ['Protect II'] = { 'Protect' },
  ['Protect III'] = { 'Protect' },
  ['Protect IV'] = { 'Protect' },
  ['Protectra'] = { 'Protect', 'Protectra' },
  ['Protectra II'] = { 'Protect', 'Protectra' },
  ['Protectra III'] = { 'Protect', 'Protectra' },
  ['Protectra IV'] = { 'Protect', 'Protectra' },
  ['Protectra V'] = { 'Protect', 'Protectra' },
  ['Refresh'] = { 'Refresh' },
  ['Regen'] = { 'Regen' },
  ['Regen II'] = { 'Regen' },
  ['Regen III'] = { 'Regen' },
  ['Shell'] = { 'Shell' },
  ['Shell II'] = { 'Shell' },
  ['Shell III'] = { 'Shell' },
  ['Shell IV'] = { 'Shell' },
  ['Shellra'] = { 'Shell', 'Shellra' },
  ['Shellra II'] = { 'Shell', 'Shellra' },
  ['Shellra III'] = { 'Shell', 'Shellra' },
  ['Shellra IV'] = { 'Shell', 'Shellra' },
  ['Shellra V'] = { 'Shell', 'Shellra' },
  ['Stoneskin'] = { 'Enhancing', 'Stoneskin' },
  ['Blaze Spikes'] = { 'Enhancing', 'Spikes', 'BlazeSpikes' },
  ['Ice Spikes'] = { 'Enhancing', 'Spikes', 'IceSpikes' },
  ['Shock Spikes'] = { 'Enhancing', 'Spikes', 'ShockSpikes' },
  ['Dread Spikes'] = { 'DreadSpikes' },

  -- Teleport Spells
  ['Escape'] = { 'Teleport', 'Escape' },
  ['Teleport-Altep'] = { 'Teleport', 'TeleportAltep' },
  ['Teleport-Dem'] = { 'Teleport', 'TeleportDem' },
  ['Teleport-Holla'] = { 'Teleport', 'TeleportHolla' },
  ['Teleport-Mea'] = { 'Teleport', 'TeleportMea' },
  ['Teleport-Vahzl'] = { 'Teleport', 'TeleportVahzl' },
  ['Teleport-Yhoat'] = { 'Teleport', 'TeleportYhoat' },
  ['Tractor'] = { 'Teleport', 'Tractor' },
  ['Warp'] = { 'Teleport', 'Warp' },
  ['Warp II'] = { 'Teleport', 'Warp' },

  -- Cure Spells
  ['Cure'] = { 'Healing', 'Cure' },
  ['Cure II'] = { 'Healing', 'Cure' },
  ['Cure III'] = { 'Healing', 'Cure' },
  ['Cure IV'] = { 'Healing', 'Cure' },
  ['Cure V'] = { 'Healing', 'Cure' },
  ['Curaga'] = { 'Healing', 'Cure', 'Curaga' },
  ['Curaga II'] = { 'Healing', 'Cure', 'Curaga' },
  ['Curaga III'] = { 'Healing', 'Cure', 'Curaga' },
  ['Curaga IV'] = { 'Healing', 'Cure', 'Curaga' },

  -- Status Removal Spells
  ['Poisona'] = { 'StatusRemoval', 'Poisona' },
  ['Paralyna'] = { 'StatusRemoval', 'Paralyna' },
  ['Silena'] = { 'StatusRemoval', 'Silena' },
  ['Blindna'] = { 'StatusRemoval', 'Blindna' },
  ['Cursna'] = { 'Healing', 'StatusRemoval', 'Cursna' },
  ['Stona'] = { 'StatusRemoval', 'Stona' },
  ['Viruna'] = { 'StatusRemoval', 'Viruna' },
  ['Erase'] = { 'StatusRemoval', 'Erase' },

  -- Raise Spells
  ['Raise'] = { 'Raise' },
  ['Raise II'] = { 'Raise' },
  ['Raise III'] = { 'Raise' },
  ['Reraise'] = { 'Raise', 'Reraise' },
  ['Reraise II'] = { 'Raise', 'Reraise' },
  ['Reraise III'] = { 'Raise', 'Reraise' },

  -- Dia/Bio Spells
  ['Dia'] = { 'Dia' },
  ['Dia II'] = { 'Dia' },
  ['Dia III'] = { 'Dia' },
  ['Diaga'] = { 'Dia', 'Diaga' },
  ['Bio'] = { 'Dark', 'Bio' },
  ['Bio II'] = { 'Dark', 'Bio' },
  ['Bio III'] = { 'Dark', 'Bio' },

  -- Misc Spells
  ['Stun'] = { 'Dark', 'Stun' },
  ['Flash'] = { 'Divine', 'Flash' },
}

return {
  name = 'Tags',
  install = function(profile)
    profile.store:watch('action', function(action)
      action.Tags = Tags[action.Name]
    end)
  end,
}
